Setup Author Envionment
ONSdigital/eq-author-terraform pull request #1
Opened 2018-11-27 12:21 UTC by jonnyshaw89

2018-11-28 10:02 UTC, samiwel commented
Tested spinning it up and tearing it down. Seems to work fine. Was able to sign in, create a simple questionnaire and preview in runner. 🤷‍♂️ LGTM

2018-11-28 10:08 UTC, samiwel approved these changes

2018-11-30 15:50 UTC, ajmaddaford requested changes

2018-11-30 15:50 UTC, ajmaddaford commented on README.md
> +slack_webhook_path=""
Also `author_firebase_project_id` and `author_firebase_api_key`

2018-11-30 15:50 UTC, ajmaddaford commented on README.md
> +slack_webhook_path=""
These used to be defaulted in eq-terraform to something made up so that they weren't needed in the default setup of auth being off.

2018-11-30 16:12 UTC, jonnyshaw89 commented on README.md
> +slack_webhook_path=""
Updated

2018-11-30 16:25 UTC, ajmaddaford approved these changes

2018-12-03 14:45 UTC, merged