Added config for new users table
ONSdigital/eq-author-terraform pull request #10
Opened 2019-05-07 07:09 UTC by SamGodwin2

This Pr adds the config required to create a new users table in the dynamo db.

Review by checking out this branch and change the source of the author-dynamodb module to `github.com/ONSdigital/eq-author-terraform-dynamodb?ref=976-map-our-user-type-to-a-table` and attempting to spin up a personal instance, if all works as expected everything should work as before just with the addition of a new db table.

2019-05-07 07:10 UTC, SamGodwin2 commented
![](https://github.trello.services/images/mini-trello-icon.png) [Map our user type to a table. (6)](https://trello.com/c/b5tDb8j3/976-map-our-user-type-to-a-table-6)

2019-05-09 08:25 UTC, tgandrews requested changes
As discussed we need to update the iam policy for api to allow for accessing the user table

2019-05-15 09:10 UTC, samiwel requested changes

2019-05-15 09:10 UTC, samiwel commented on author.tf
> +              "dynamodb:DeleteItem"
Is the delete permission needed? Best to remove it if not.

2019-05-15 14:14 UTC, tgandrews approved these changes

2019-05-16 06:44 UTC, tgandrews commented
Need to also make this change in `eq-deploy` for preprod and prod

2019-05-16 08:29 UTC, samiwel approved these changes

2019-06-10 07:33 UTC, merged