Add ability to read secrets from S3 bucket.
ONSdigital/eq-author-terraform pull request #18
Opened 2019-06-13 11:57 UTC by samiwel

### What is the context of this PR?
Author API needs the ability to be able to read a Firebase service account key, which is unique for each environment).

This change introduces a couple of new variables to the Author terraform configuration to allow the API to sync and load its secret keys from an S3 bucket.

### How to test
- Create a firebase project and generate a new service account key for the project.
- Place the JSON key file in an S3 bucket in the dev account.
- Set the new variables appropriately.
- Ensure that `author_tag` variable is pointing at this branch: https://github.com/ONSdigital/eq-author-app/pull/369.
- Run terraform and ensure that API loads key from the S3 bucket (look at Cloudwatch logs on container start up).
- Remember to run `terraform destroy` after you're finished.

2019-06-17 11:29 UTC, jonnyshaw89 reviewed
How do you envisage this working?
Maybe the Readme needs updating to let people know what to do?
Or we create a common bucket with a default dev key?

2019-06-17 11:47 UTC, samiwel commented
@jonnyshaw89 During local development, devs typically use their own Firebase environments and so its currently part of the developer setup to create a service account key for verifying Firebase tokens on the API. This has been added to the README in https://github.com/ONSdigital/eq-author-app/pull/369.

The S3 bucket is only really needed for deploying to the staging, preprod and prod environments. Each environment has an equivalent Firebase project, so they service account key will be different in each environment. But each environment can retrieve its key from `$SECRETS_S3_BUCKET`.

2019-06-17 11:51 UTC, jonnyshaw89 commented
So this repo will no longer allow for devs to deploy their own environment to AWS?
As a dev would need to create and S3 bucket and deploy their own key? which isn't accounted for in this repos Readme.

2019-06-17 11:52 UTC, jonnyshaw89 commented on author.tf
> +          "Resource": "arn:aws:s3:::*"
I would use `${var.author_secrets_bucket_name}` to restrict access to only the bucket required

2019-06-17 11:57 UTC, samiwel commented
You're right, but same goes for the existing firebase variables as well there's no documentation about setting these up either. I'll add some docs to the README.

2019-06-17 13:22 UTC, jonnyshaw89 requested changes

2019-06-17 13:22 UTC, jonnyshaw89 commented on README.md
> +author_firebase_service_account_key=""
its unclear here that the contents of the s3 bucket will be synced to the container under the `/secrets` folder. (https://github.com/ONSdigital/eq-author-app/blob/master/eq-author-api/docker-entrypoint.sh#L5)
So we should make it clear that this path need to be the absolute path of that file inside the container after the sync

2019-06-17 13:31 UTC, jonnyshaw89 commented on README.md
> +# If syncing from S3 (see below) this will be something like '/secrets/path-to-key-file.json'
> If syncing from S3

What other options are there? without a key you can't login?

2019-06-17 13:51 UTC, samiwel commented
This does make the setup for devs a bit more painful, but the other option we considered was to make the token verification optional step optional and only verify tokens in environments where the key file variable has been set. But we decided against this because it opens up the possibility of incorrectly configuring an environment with token verification turned off and ideally we want development environments to be as representative of the production environment as possible.

2019-06-18 09:01 UTC, samiwel commented
I am closing this PR since it won't be required if we use a different approach to verify the tokens, as described here: https://firebase.google.com/docs/auth/admin/verify-id-tokens#verify_id_tokens_using_a_third-party_jwt_library

2019-06-18 09:01 UTC, closed without merging